### ISSUE TITLE
Program does not handle lowercase characters properly & Missing new line b4 exit

### ISSUE THREAD

**Issue by qhga** [TheDonDope/gordle#4]
Dear developer,

when I play your game, I never win... That makes me sad... :sob: :sob:

Here is my last result:

```Your Gordle results (2022-01-16):
lower ⬛⬛⬛⬛⬛ (1/6)
cases ⬛⬛⬛⬛⬛ (2/6)
arent ⬛⬛⬛⬛⬛ (3/6)
worki ⬛⬛⬛⬛⬛ (4/6)
pleez ⬛⬛⬛⬛⬛ (5/6)
fixit ⬛⬛⬛⬛⬛ (6/6)

The solution was: NEQUE /tmp/gordle/cmd/cli
$ Give me my newline back!
```
I guess there is a bug which is intendet to make me look bad. :rage: 
The pesky :bug: can be observed in the games output! :mag: 

Good game 10/10 :rocket: :fire: 

plz don't overuse :smile:'s and implement `strings.ToLower(str)` ty! :1st_place_medal:

**Comment by TheDonDope** [comment]
Hello @qhga ,

Thank you for the issue, here are the fixes: 
- https://github.com/TheDonDope/gordle/commit/88b50198f662d2b4d8f5d836d44cf7a1e2dc4844
- https://github.com/TheDonDope/gordle/commit/fb0286aa5d49b2f2d53c598a389553eea7592bcc
